databases:
  - name: mcd_DB
    databaseName: mcd_db
    user: Mcd
    region: singapore

services:
  - type: web
    name: Mcd
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mcd_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

